name: Officetel Watcher

on:
  schedule:
    - cron: "*/5 * * * *"   # 5분마다
  workflow_dispatch: {}     # 수동 실행 버튼

permissions:
  contents: write  # seen.json 커밋하려면 필요

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run watcher
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python watch_officetel.py

      - name: Persist seen.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f seen.json ]; then
            git add seen.json
            git diff --cached --quiet || git commit -m "update seen.json"
            git push
          fi
